import type { Metadata } from "next";
import "./globals.css";
import { Inter, Roboto_Mono, Corinthia } from 'next/font/google';
import localFont from 'next/font/local';

export const metadata: Metadata = {
  title: "Psynexa - Task",
  description: "Generated by Altug",
};

const clashDisplay = localFont({
  src: [
    { path: './fonts/ClashDisplay-Extralight.woff2', weight: '200', style: 'normal' },
    { path: './fonts/ClashDisplay-Light.woff2', weight: '300', style: 'normal' },
    { path: './fonts/ClashDisplay-Regular.woff2', weight: '400', style: 'normal' },
    { path: './fonts/ClashDisplay-Medium.woff2', weight: '500', style: 'normal' },
    { path: './fonts/ClashDisplay-Semibold.woff2', weight: '600', style: 'normal' },
    { path: './fonts/ClashDisplay-Bold.woff2', weight: '700', style: 'normal' },
  ],
  variable: '--font-clash-display',
});

const cabinetGrotesk = localFont({
  src: [
    { path: './fonts/CabinetGrotesk-Thin.woff2', weight: '100', style: 'normal' },
    { path: './fonts/CabinetGrotesk-Extralight.woff2', weight: '200', style: 'normal' },
    { path: './fonts/CabinetGrotesk-Light.woff2', weight: '300', style: 'normal' },
    { path: './fonts/CabinetGrotesk-Regular.woff2', weight: '400', style: 'normal' },
    { path: './fonts/CabinetGrotesk-Medium.woff2', weight: '500', style: 'normal' },
    { path: './fonts/CabinetGrotesk-Bold.woff2', weight: '700', style: 'normal' },
    { path: './fonts/CabinetGrotesk-Extrabold.woff2', weight: '800', style: 'normal' },
    { path: './fonts/CabinetGrotesk-Black.woff2', weight: '900', style: 'normal' },
  ],
  variable: '--font-cabinet-grotesk',
});

const inter = Inter({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-inter',
})

const roboto_mono = Roboto_Mono({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-roboto-mono',
})

const corinthia = Corinthia({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-corinthia',
  weight: "400"
})


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${inter.variable} ${roboto_mono.variable} ${corinthia.variable} ${clashDisplay.variable} ${cabinetGrotesk.variable}`}>
      <body>{children}</body>
    </html>
  );
}
